# DataPlane for sample-org
# Manages via GitOps - credentials referenced from secrets (not inline)
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default
  namespace: sample-org
  annotations:
    openchoreo.dev/description: Default DataPlane for sample-org organization
    openchoreo.dev/display-name: Sample Org DataPlane
  labels:
    openchoreo.dev/name: default
    openchoreo.dev/organization: sample-org
spec:
  # Cluster agent configuration for secure communication
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        key: ca.crt

  # Gateway configuration for routing traffic
  gateway:
    organizationVirtualHost: sample-org.internal
    publicVirtualHost: sample-org.localhost

  # Unique identifier for this dataplane
  planeID: sample-org-dataplane

  # Reference to the secret store (Vault) for external secrets
  secretStoreRef:
    name: vault-cluster-store

  # Reference to observability plane for metrics/logs
  observabilityPlaneRef: default
