# DataPlane for acme
# Manages via GitOps - credentials referenced from secrets (not inline)
apiVersion: openchoreo.dev/v1alpha1
kind: DataPlane
metadata:
  name: default
  namespace: acme
  annotations:
    openchoreo.dev/description: Default DataPlane for acme organization
    openchoreo.dev/display-name: Acme DataPlane
  labels:
    openchoreo.dev/name: default
    openchoreo.dev/organization: acme
spec:
  # Cluster agent configuration for secure communication
  clusterAgent:
    clientCA:
      secretRef:
        name: cluster-gateway-ca
        key: ca.crt

  # Gateway configuration for routing traffic
  gateway:
    organizationVirtualHost: acme.internal
    publicVirtualHost: acme.localhost

  # Use existing cluster-agent's planeID to share the dataplane agent
  # In production, each organization would have its own cluster-agent
  planeID: default-dataplane

  # Reference to the secret store (Vault) for external secrets
  secretStoreRef:
    name: vault-cluster-store

  # Reference to observability plane for metrics/logs
  observabilityPlaneRef: default
